load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "browse",
    srcs = ["browse.py"],
    main = "browse.py",
    deps = ["//misc:ninja_syntax"],
)

cc_library(
    name = "elide_middle",
    srcs = ["elide_middle.cc"],
    hdrs = ["elide_middle.h"],
    visibility = ["//visibility:public"],
)

# Disk interface library for tests.
cc_library(
    name = "disk_interface",
    srcs = ["disk_interface.cc"],
    hdrs = ["disk_interface.h", "timestamp.h"],
    visibility = ["//visibility:public"],
)

# Test support library for C++ tests.
cc_library(
    name = "test_support",
    hdrs = ["test.h"],
    deps = ["@googletest//:gtest"],
)

cc_test(
    name = "elide_middle_test",
    srcs = ["elide_middle_test.cc"],
    deps = [":elide_middle", ":test_support", ":disk_interface", "@googletest//:gtest_main"],
)
