load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "string_piece",
    hdrs = ["string_piece.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "string_piece_util",
    srcs = ["string_piece_util.cc"],
    hdrs = ["string_piece_util.h"],
    deps = [":string_piece"],
    visibility = ["//visibility:public"],
)
