load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "string_piece",
    hdrs = ["string_piece.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "string_piece_util",
    srcs = ["string_piece_util.cc"],
    hdrs = ["string_piece_util.h"],
    deps = [":string_piece"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "edit_distance",
    srcs = ["edit_distance.cc"],
    hdrs = ["edit_distance.h"],
    deps = [":string_piece"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "elide_middle",
    srcs = ["elide_middle.cc"],
    hdrs = ["elide_middle.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "getopt",
    srcs = ["getopt.c"],
    hdrs = ["getopt.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "json",
    srcs = ["json.cc"],
    hdrs = ["json.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "exit_status",
    hdrs = ["exit_status.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "load_status",
    hdrs = ["load_status.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "timestamp",
    hdrs = [
        "timestamp.h",
        "win32port.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "explanations",
    hdrs = ["explanations.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "eval_env",
    srcs = ["eval_env.cc"],
    hdrs = ["eval_env.h"],
    deps = [":string_piece"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "status",
    hdrs = ["status.h"],
    deps = [":exit_status"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "util",
    srcs = ["util.cc"],
    hdrs = ["util.h"],
    deps = [
        ":edit_distance",
        ":string_piece_util",
        ":timestamp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "rapidhash",
    hdrs = ["third_party/rapidhash/rapidhash.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "emhash",
    hdrs = ["third_party/emhash/hash_table8.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "hash_map",
    hdrs = ["hash_map.h"],
    deps = [
        ":emhash",
        ":rapidhash",
        ":string_piece",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "metrics",
    srcs = ["metrics.cc"],
    hdrs = ["metrics.h"],
    deps = [":util"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "line_printer",
    srcs = ["line_printer.cc"],
    hdrs = ["line_printer.h"],
    deps = [
        ":elide_middle",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "version",
    srcs = ["version.cc"],
    hdrs = ["version.h"],
    deps = [":util"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "disk_interface",
    srcs = ["disk_interface.cc"],
    hdrs = ["disk_interface.h"],
    deps = [
        ":metrics",
        ":timestamp",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "jobserver",
    srcs = ["jobserver.cc"] + select({
        "@bazel_tools//src/conditions:windows": ["jobserver-win32.cc"],
        "//conditions:default": ["jobserver-posix.cc"],
    }),
    hdrs = ["jobserver.h"],
    deps = [
        ":string_piece",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "subprocess",
    srcs = select({
        "@bazel_tools//src/conditions:windows": ["subprocess-win32.cc"],
        "//conditions:default": ["subprocess-posix.cc"],
    }),
    hdrs = ["subprocess.h"],
    deps = [
        ":exit_status",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "depfile_parser",
    srcs = ["depfile_parser.cc"],
    hdrs = ["depfile_parser.h"],
    deps = [
        ":string_piece",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lexer",
    srcs = ["lexer.cc"],
    hdrs = ["lexer.h"],
    deps = [
        ":eval_env",
        ":string_piece",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "parser",
    srcs = ["parser.cc"],
    hdrs = ["parser.h"],
    deps = [
        ":disk_interface",
        ":lexer",
        ":metrics",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "includes_normalize",
    srcs = select({
        "@bazel_tools//src/conditions:windows": ["includes_normalize-win32.cc"],
        "//conditions:default": [],
    }),
    hdrs = ["includes_normalize.h"],
    deps = [
        ":string_piece",
        ":string_piece_util",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clparser",
    srcs = ["clparser.cc"],
    hdrs = ["clparser.h"],
    deps = [
        ":includes_normalize",
        ":metrics",
        ":string_piece",
        ":string_piece_util",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "msvc_helper",
    srcs = select({
        "@bazel_tools//src/conditions:windows": ["msvc_helper-win32.cc"],
        "//conditions:default": [],
    }),
    hdrs = ["msvc_helper.h"],
    deps = [":util"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "minidump",
    srcs = select({
        "@bazel_tools//src/conditions:windows": ["minidump-win32.cc"],
        "//conditions:default": [],
    }),
    deps = [":util"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "graph",
    srcs = [
        "build.cc",
        "build_log.cc",
        "debug_flags.cc",
        "deps_log.cc",
        "dyndep.cc",
        "dyndep_parser.cc",
        "graph.cc",
        "manifest_parser.cc",
        "real_command_runner.cc",
        "state.cc",
    ],
    hdrs = [
        "build.h",
        "build_log.h",
        "debug_flags.h",
        "deps_log.h",
        "dyndep.h",
        "dyndep_parser.h",
        "graph.h",
        "manifest_parser.h",
        "state.h",
    ],
    deps = [
        ":clparser",
        ":depfile_parser",
        ":disk_interface",
        ":edit_distance",
        ":eval_env",
        ":exit_status",
        ":explanations",
        ":hash_map",
        ":jobserver",
        ":load_status",
        ":metrics",
        ":parser",
        ":status",
        ":subprocess",
        ":timestamp",
        ":util",
        ":version",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "clean",
    srcs = ["clean.cc"],
    hdrs = ["clean.h"],
    deps = [
        ":disk_interface",
        ":graph",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "graphviz",
    srcs = ["graphviz.cc"],
    hdrs = ["graphviz.h"],
    deps = [":graph"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "missing_deps",
    srcs = ["missing_deps.cc"],
    hdrs = ["missing_deps.h"],
    deps = [
        ":depfile_parser",
        ":disk_interface",
        ":graph",
        ":util",
    ],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "status_printer",
    srcs = ["status_printer.cc"],
    hdrs = ["status_printer.h"],
    deps = [
        ":exit_status",
        ":explanations",
        ":graph",
        ":line_printer",
        ":status",
        ":timestamp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "command_collector",
    hdrs = ["command_collector.h"],
    deps = [":graph"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "browse_py_h",
    srcs = ["browse.py"],
    tools = ["inline.sh"],
    outs = ["browse_py.h"],
    cmd = "$(location inline.sh) kBrowsePy < $(location browse.py) > $@",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "browse",
    srcs = ["browse.cc"],
    hdrs = [
        "browse.h",
    ],
    deps = [
        ":browse_py_h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "libninja",
    deps = [
        ":browse",
        ":clean",
        ":clparser",
        ":command_collector",
        ":depfile_parser",
        ":disk_interface",
        ":edit_distance",
        ":elide_middle",
        ":explanations",
        ":getopt",
        ":graph",
        ":graphviz",
        ":includes_normalize",
        ":jobserver",
        ":json",
        ":lexer",
        ":minidump",
        ":missing_deps",
        ":msvc_helper",
        ":status_printer",
        ":string_piece_util",
        ":subprocess",
        ":util",
    ],
    visibility = ["//visibility:public"],
)

# Test Utilities
# ==============

cc_library(
    name = "test_util",
    srcs = ["test.cc"],
    hdrs = ["test.h"],
    deps = [
        ":disk_interface",
        ":graph",
        "@googletest//:gtest",
    ],
)

# Test Suite
# ==========

cc_test(
    name = "ninja_test",
    srcs = [
        "build_log_test.cc",
        "build_test.cc",
        "clean_test.cc",
        "clparser_test.cc",
        "depfile_parser_test.cc",
        "deps_log_test.cc",
        "disk_interface_test.cc",
        "dyndep_parser_test.cc",
        "edit_distance_test.cc",
        "elide_middle_test.cc",
        "explanations_test.cc",
        "graph_test.cc",
        "jobserver_test.cc",
        "json_test.cc",
        "lexer_test.cc",
        "manifest_parser_test.cc",
        "missing_deps_test.cc",
        "ninja_test.cc",
        "state_test.cc",
        "string_piece_util_test.cc",
        "subprocess_test.cc",
        "util_test.cc",
    ] + select({
        "@bazel_tools//src/conditions:windows": [
            "includes_normalize_test.cc",
            "msvc_helper_test.cc",
        ],
        "//conditions:default": [],
    }),
    deps = [
        ":libninja",
        ":test_util",
        "@googletest//:gtest_main",
    ],
)

# Performance Tests
# =================

cc_binary(
    name = "build_log_perftest",
    srcs = ["build_log_perftest.cc"],
    deps = [":graph"],
)

cc_binary(
    name = "canon_perftest",
    srcs = ["canon_perftest.cc"],
    deps = [
        ":metrics",
        ":util",
    ],
)

cc_binary(
    name = "clparser_perftest",
    srcs = ["clparser_perftest.cc"],
    deps = [
        ":clparser",
        ":metrics",
    ],
)

cc_binary(
    name = "depfile_parser_perftest",
    srcs = ["depfile_parser_perftest.cc"],
    deps = [
        ":depfile_parser",
        ":metrics",
        ":util",
    ],
)

cc_binary(
    name = "elide_middle_perftest",
    srcs = ["elide_middle_perftest.cc"],
    deps = [
        ":elide_middle",
        ":metrics",
    ],
)

cc_binary(
    name = "hash_collision_bench",
    srcs = ["hash_collision_bench.cc"],
    deps = [":graph"],
)

cc_binary(
    name = "manifest_parser_perftest",
    srcs = ["manifest_parser_perftest.cc"],
    deps = [
        ":disk_interface",
        ":getopt",
        ":graph",
    ],
)

filegroup(
    name = "perftests",
    srcs = [
        ":build_log_perftest",
        ":canon_perftest",
        ":clparser_perftest",
        ":depfile_parser_perftest",
        ":elide_middle_perftest",
        ":hash_collision_bench",
        ":manifest_parser_perftest",
    ],
    visibility = ["//visibility:public"],
)

# Main Executable
# ===============

cc_binary(
    name = "ninja",
    srcs = ["ninja.cc"],
    copts = ["-DNINJA_HAVE_BROWSE"],
    deps = [
        ":libninja",
    ],
)
